---
fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    concat: https://github.com/puppetlabs/puppetlabs-concat
    apt: https://github.com/puppetlabs/puppetlabs-apt
    zypprepo: https://github.com/voxpupuli/puppet-zypprepo
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core
    chocolatey: https://github.com/puppetlabs/puppetlabs-chocolatey
    redis: https://github.com/voxpupuli/puppet-redis
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core
    icinga2: https://github.com/voxpupuli/puppet-icinga2
